{% set name = "jupyter-forward" %}
{% set version = "2025.1.16" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8d5baeb46c05908660be9c67396ec1e887dac01102feb9fa3c9af5cae7662b49

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-forward=jupyter_forward.cli:main
    - jlab-forward=jupyter_forward.cli:main
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - typer >=0.4
    - fabric >=2.5
    - rich >=11.0.0

test:
  imports:
    - jupyter_forward
  commands:
    # - pip check
    - jupyter-forward --help
    - jlab-forward --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NCAR/jupyter-forward
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/NCAR/jupyter-forward
  doc_url: https://jupyter-forward.readthedocs.io
  summary: Jupyter Lab Port Forwarding Utility
  description: |
    Jupyter-forward simplifies the process of running jupyter lab on a remote machine by performing the following tasks on behalf of the users:

    1. Logging into a remote cluster/resource via the SSH protocol.
    2. Launching Jupyter Lab on the remote cluster.
    3. Port forwarding Jupyter Lab session back to your local machine.
    4. Opening the port forwarded Jupyter Lab session into your local browser.

extra:
  recipe-maintainers:
    - andersy005
    - mnlevy1981
    - mgrover1
    - jukent
    - kmpaul
